/// Flutter icons MoneyIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MoneyIcons
///      fonts:
///       - asset: fonts/MoneyIcons.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MoneyIcons {
  MoneyIcons._();

  static const _kFontFam = 'MoneyIcons';

  static const IconData wallet = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData money = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData dollar = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData money_1 = const IconData(0xf0d6, fontFamily: _kFontFam);
}
